language: python
python:
    - "3.6"
install:
  - pip install -r requirements.txt

addons:
  chrome: stable

script: python -m unittest discover tests

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.26/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6/bin/
  - export CHROME_BIN=chromium-browser